services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    env_file:
      - ./backend/.env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
